# Practica #1 

**Nombre:** Ricardo Leon
**Curso:** GR2CD

In [1]:
# Leer json

In [2]:
import json
import pandas as pd

In [10]:
datos = r"C:\Users\P4E010-T\Documents\estadistica\IDSD422-lab1-lectura-datos\data\ventas.json"
with open(datos, encoding="utf-8") as f:
  datos = json.load(f)

  # Imprime las primeras filas
  ventas = pd.json_normalize(datos)
  print(ventas.head())

  # Las dimenciones de la tabla
  print ('\nDimenciones',ventas.shape)

  # Imprime los tipos de columna
  print('\n Tipos por columna' )
  print(ventas.dtypes)

           sucursal  region  ventas  clientes
0       Quito Norte  Sierra   12450       320
1         Quito Sur  Sierra    9870       265
2  Guayaquil Centro   Costa   15200       410
3   Guayaquil Norte   Costa   13980       372
4            Cuenca  Sierra    8540       210

Dimenciones (5, 4)

 Tipos por columna
sucursal      str
region        str
ventas      int64
clientes    int64
dtype: object

# Leer excel

In [ ]:
import pandas as pd

In [14]:
data = r"C:\Users\P4E010-T\Documents\estadistica\IDSD422-lab1-lectura-datos\data\ventas.xlsx"
ventas = pd.read_excel(data,sheet_name="ventas", engine="calamine")

In [15]:
ventas

           sucursal  region  ventas  clientes
0       Quito Norte  Sierra   12450       320
1         Quito Sur  Sierra    9870       265
2  Guayaquil Centro   Costa   15200       410
3   Guayaquil Norte   Costa   13980       372
4            Cuenca  Sierra    8540       210

In [ ]:
ventas.head()

           sucursal  region  ventas  clientes
0       Quito Norte  Sierra   12450       320
1         Quito Sur  Sierra    9870       265
2  Guayaquil Centro   Costa   15200       410
3   Guayaquil Norte   Costa   13980       372
4            Cuenca  Sierra    8540       210

In [18]:
ventas.shape
ventas.dtypes

sucursal      str
region        str
ventas      int64
clientes    int64
dtype: object